# Basic site info
title:              "Jean Pamphile"
description:        "Computer Science Student"

# Site URL settings
url:                https://jpamphile.github.io # main url
baseurl:            /cv # for gh-pages

# Google Analytics ID
google_analytics_code: 

# Build settings
source:             ./
destination:        ./_site
markdown:           kramdown
highlighter:        rouge
timezone:           America/New_York
exclude:            ["README.md", "LICENSE.md", "CHANGELOG.md"]

# Site configurations
compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  endings:          all
  ignore:
    envs:           [local]
  blanklines:       false
  profile:          false
  startings:        [html, head, body]

sass:
  sass_dir:         assets/scss
  style:            compressed # expanded
